# TAPD Bug Reporter - Credential Encryption Tool
# Usage: Double-click the shortcut (created once via steps in README.md)
# Admin enters API username and password, script generates encrypted credentials

# ===== Parameters (must match background.js) =====
$Passphrase = 'R7kQ2mZ9xW4vN1pL8jF6yH3tB5cA0sD'
$SaltB64    = 'B58EUkqXDtCMSgpEgcKnyA=='

# ===== Helper Functions =====

function Convert-FromBase64($b64) {
    return [Convert]::FromBase64String($b64)
}

function Convert-ToBase64($bytes) {
    return [Convert]::ToBase64String($bytes)
}

function Derive-Key($passphrase, $saltBytes) {
    $pbkdf2 = New-Object System.Security.Cryptography.Rfc2898DeriveBytes(
        $passphrase, $saltBytes, 100000, [System.Security.Cryptography.HashAlgorithmName]::SHA256
    )
    return $pbkdf2.GetBytes(32)
}

function Encrypt-Aes256CbcHmac($key, $iv, $plaintext) {
    # AES-256-CBC + HMAC-SHA256 (compatible with PowerShell 5.1 / .NET 4.x)
    $aes = New-Object System.Security.Cryptography.AesCryptoServiceProvider
    $aes.Key = $key
    $aes.IV = $iv  # AES-CBC requires 16-byte IV
    $aes.Mode = [System.Security.Cryptography.CipherMode]::CBC
    $aes.Padding = [System.Security.Cryptography.PaddingMode]::PKCS7

    $plaintextBytes = [System.Text.Encoding]::UTF8.GetBytes($plaintext)
    $encryptor = $aes.CreateEncryptor()
    $cipherBytes = $encryptor.TransformFinalBlock($plaintextBytes, 0, $plaintextBytes.Length)
    $encryptor.Dispose()

    # HMAC-SHA256 over (IV || ciphertext)
    $hmacData = New-Object byte[] ($iv.Length + $cipherBytes.Length)
    [Array]::Copy($iv, 0, $hmacData, 0, $iv.Length)
    [Array]::Copy($cipherBytes, 0, $hmacData, $iv.Length, $cipherBytes.Length)
    $hmac = New-Object System.Security.Cryptography.HMACSHA256
    $hmac.Key = $key
    $signature = $hmac.ComputeHash($hmacData)
    $hmac.Dispose()

    # Output: IV(16) + ciphertext + HMAC(32)
    $result = New-Object byte[] ($iv.Length + $cipherBytes.Length + $signature.Length)
    [Array]::Copy($iv, 0, $result, 0, $iv.Length)
    [Array]::Copy($cipherBytes, 0, $result, $iv.Length, $cipherBytes.Length)
    [Array]::Copy($signature, 0, $result, $iv.Length + $cipherBytes.Length, $signature.Length)

    $aes.Dispose()
    return Convert-ToBase64 $result
}

# ===== Main =====

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  TAPD Bug Reporter - Credential Encrypt Tool" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

$apiUser = Read-Host "Please enter API username"
$apiPassword = Read-Host "Please enter API password" -AsSecureString
$apiPasswordPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($apiPassword)
)

if (-not $apiUser -or -not $apiPasswordPlain) {
    Write-Host "[ERROR] Username and password cannot be empty" -ForegroundColor Red
    exit 1
}

$saltBytes = Convert-FromBase64 $SaltB64
$key = Derive-Key $Passphrase $saltBytes

$iv = New-Object byte[] 16
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($iv)
$ivB64 = Convert-ToBase64 $iv

Write-Host ""
Write-Host "Encrypting..." -ForegroundColor Yellow

$userEnc = Encrypt-Aes256CbcHmac $key $iv $apiUser
$passEnc = Encrypt-Aes256CbcHmac $key $iv $apiPasswordPlain

$apiPasswordPlain = $null
[GC]::Collect()

Write-Host "Encryption done!" -ForegroundColor Green
Write-Host ""

$encFilePath = Join-Path $PSScriptRoot "credentials.enc.js"
$lines = @(
    "// ===== TAPD API Encrypted Credentials (Admin Config) =====",
    "// Generated by encrypt-credentials.ps1",
    "// DO NOT edit this file manually",
    "",
    "var CREDENTIALS_ENCRYPTED = {",
    "  api_url: 'https://api.tapd.cn',",
    ("  api_user_enc: '" + $userEnc + "',"),
    ("  api_password_enc: '" + $passEnc + "',"),
    ("  iv: '" + $ivB64 + "'"),
    "};"
)
$encContent = $lines -join "`n"

[System.IO.File]::WriteAllText($encFilePath, $encContent, (New-Object System.Text.UTF8Encoding $false))

Write-Host "Written: $encFilePath" -ForegroundColor Green
Write-Host ""
Write-Host "NOTE: credentials.enc.js is in .gitignore and will NOT be committed" -ForegroundColor Yellow